# Generated by Django 3.2.23 on 2023-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_and_cs', '0002_alter_userverified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverified',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
