# Generated by Django 3.2.23 on 2023-12-05 14:23

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('bike_part', 'Bike Part'), ('bike_accessory', 'Bike Accessory'), ('other', 'Other')], default='other', max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('tired', 'Tired'), ('like_new', 'Like New'), ('used', 'Used')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=50)),
                ('approved', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
