# Generated by Django 3.2.23 on 2023-12-09 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20231207_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='trading_placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
