# Generated by Django 3.2.23 on 2023-12-13 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ride_images/')),
                ('route_description', models.TextField()),
                ('start_place', models.CharField(max_length=200)),
                ('end_place', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difficulty', models.CharField(choices=[('BF', 'Beginner Friendly'), ('IN', 'Intermediate'), ('CH', 'Challenging'), ('EX', 'Seasoned Experts Advised')], default='BF', max_length=2)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideOrganiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_organiser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_rides', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='social_rides.ride')),
            ],
        ),
    ]
