# Generated by Django 3.2.23 on 2023-12-13 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
