# Generated by Django 3.2.23 on 2023-12-13 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_rides', '0002_ride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
