# Generated by Django 3.2.23 on 2023-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_rides', '0003_ride_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
