# Generated by Django 3.2.23 on 2023-11-29 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_detail_bullets',
        ),
        migrations.AddField(
            model_name='service',
            name='description_summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
