# Generated by Django 3.2.23 on 2023-12-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0003_auto_20231130_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_slots', to='bookable_services.slot')),
            ],
        ),
    ]
