# Generated by Django 3.2.23 on 2023-12-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0004_individualslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='individual_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.individualslot'),
        ),
    ]
