# Generated by Django 3.2.23 on 2023-12-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0006_auto_20231215_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.service'),
        ),
    ]
