# Generated by Django 3.2.23 on 2023-12-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0010_auto_20231215_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
