# Generated by Django 3.2.23 on 2023-12-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0012_booking_serviceslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslot',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.service'),
        ),
    ]
