# Generated by Django 3.2.23 on 2023-12-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0013_alter_serviceslot_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.serviceslot'),
        ),
    ]
