# Generated by Django 3.2.23 on 2023-12-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookable_services', '0014_alter_booking_service_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('further_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_people', models.IntegerField(default=1)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookable_services.place')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_slot',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='key_features',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_detail_bullets',
            field=models.TextField(default='Details not provided.'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_summary',
            field=models.TextField(default='No summary available.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ServiceSlot',
        ),
        migrations.AddField(
            model_name='slot',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookable_services.slot'),
        ),
        migrations.AddField(
            model_name='service',
            name='regions',
            field=models.ManyToManyField(to='bookable_services.Place'),
        ),
    ]
