# Generated by Django 3.2.23 on 2023-11-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='Content',
            new_name='content',
        ),
    ]
