# Generated by Django 3.2.23 on 2023-11-28 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_rename_content_forumpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
