# Generated by Django 3.2.23 on 2023-12-11 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_forumpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='published_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='reported_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
