# Generated by Django 3.2.23 on 2023-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20231211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='published_status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=1),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='reported_status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
