# Generated by Django 3.2.23 on 2023-11-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20231128_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='cycling_skills',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('casual', 'Casual'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='maintenance_skills',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('casual', 'Casual'), ('basic', 'Basic'), ('advanced', 'Advanced'), ('youtube_is_my_hero', 'YouTube is my hero!')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='preferred_ride_type',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('electric', 'Electric'), ('bmx', 'BMX'), ('mountain', 'Mountain'), ('hybrid', 'Hybrid')], default='road', max_length=100, null=True),
        ),
    ]
