# Generated by Django 3.2.23 on 2023-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20231130_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='preferred_ride_type',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('electric', 'Electric'), ('bmx', 'BMX'), ('mountain', 'Mountain'), ('hybrid', 'Hybrid')], max_length=100, null=True),
        ),
    ]
